[project]
name = "mcp-project"
version = "0.1.0"
description = "This is the MCP server that will run locally using stdio"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.2.0",
    "mcp>=1.9.0",
]
